<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="cention-QA" duration-ms="40011" started-at="2023-08-14T08:40:47Z" finished-at="2023-08-14T08:41:27Z">
    <groups>
    </groups>
    <test name="Administration" duration-ms="40011" started-at="2023-08-14T08:40:47Z" finished-at="2023-08-14T08:41:27Z">
      <class name="testCasesArea.AdministrationTC">
        <test-method status="PASS" signature="Base(java.lang.String)[pri:0, instance:testCasesArea.AdministrationTC@45afc369]" name="Base" is-config="true" duration-ms="2962" started-at="2023-08-14T16:40:47Z" finished-at="2023-08-14T16:40:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Base -->
        <test-method status="PASS" signature="loginToApplication()[pri:0, instance:testCasesArea.AdministrationTC@45afc369]" name="loginToApplication" is-config="true" duration-ms="21183" started-at="2023-08-14T16:40:50Z" finished-at="2023-08-14T16:41:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplication -->
        <test-method status="PASS" signature="verifyAccountsPage_01()[pri:0, instance:testCasesArea.AdministrationTC@45afc369]" name="verifyAccountsPage_01" duration-ms="11682" started-at="2023-08-14T16:41:11Z" finished-at="2023-08-14T16:41:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccountsPage_01 -->
        <test-method status="FAIL" signature="verifyCreateNewEmail_02()[pri:0, instance:testCasesArea.AdministrationTC@45afc369]" name="verifyCreateNewEmail_02" duration-ms="3781" started-at="2023-08-14T16:41:23Z" finished-at="2023-08-14T16:41:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:288)
	at org.testng.Assert.assertEquals(Assert.java:298)
	at testCasesArea.AdministrationTC.verifyCreateNewEmail_02(AdministrationTC.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyCreateNewEmail_02 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCasesArea.AdministrationTC@45afc369]" name="tearDown" is-config="true" duration-ms="1" started-at="2023-08-14T16:41:27Z" finished-at="2023-08-14T16:41:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCasesArea.AdministrationTC -->
    </test> <!-- Administration -->
  </suite> <!-- cention-QA -->
</testng-results>
